/*
 http://responsiveslides.com v1.54 by @viljamis */
jQuery.extend(jQuery.easing,{easeInQuad:function(e,a,b,d,c){return d*(a/=c)*a+b},easeOutQuad:function(e,a,b,d,c){return-d*(a/=c)*(a-2)+b},easeInOutQuad:function(e,a,b,d,c){return 1>(a/=c/2)?d/2*a*a+b:-d/2*(--a*(a-2)-1)+b},easeInCubic:function(e,a,b,d,c){return d*(a/=c)*a*a+b},easeOutCubic:function(e,a,b,d,c){return d*((a=a/c-1)*a*a+1)+b},easeInOutCubic:function(e,a,b,d,c){return 1>(a/=c/2)?d/2*a*a*a+b:d/2*((a-=2)*a*a+2)+b},easeInQuart:function(e,a,b,d,c){return d*(a/=c)*a*a*a+b},easeOutQuart:function(e,
a,b,d,c){return-d*((a=a/c-1)*a*a*a-1)+b},easeInOutQuart:function(e,a,b,d,c){return 1>(a/=c/2)?d/2*a*a*a*a+b:-d/2*((a-=2)*a*a*a-2)+b},easeInQuint:function(e,a,b,d,c){return d*(a/=c)*a*a*a*a+b},easeOutQuint:function(e,a,b,d,c){return d*((a=a/c-1)*a*a*a*a+1)+b},easeInOutQuint:function(e,a,b,d,c){return 1>(a/=c/2)?d/2*a*a*a*a*a+b:d/2*((a-=2)*a*a*a*a+2)+b},easeInSine:function(e,a,b,d,c){return-d*Math.cos(a/c*(Math.PI/2))+d+b},easeOutSine:function(e,a,b,d,c){return d*Math.sin(a/c*(Math.PI/2))+b},easeInOutSine:function(e,
a,b,d,c){return-d/2*(Math.cos(Math.PI*a/c)-1)+b},easeInExpo:function(e,a,b,d,c){return 0==a?b:d*Math.pow(2,10*(a/c-1))+b},easeOutExpo:function(e,a,b,d,c){return a==c?b+d:d*(-Math.pow(2,-10*a/c)+1)+b},easeInOutExpo:function(e,a,b,d,c){return 0==a?b:a==c?b+d:1>(a/=c/2)?d/2*Math.pow(2,10*(a-1))+b:d/2*(-Math.pow(2,-10*--a)+2)+b},easeInCirc:function(e,a,b,d,c){return-d*(Math.sqrt(1-(a/=c)*a)-1)+b},easeOutCirc:function(e,a,b,d,c){return d*Math.sqrt(1-(a=a/c-1)*a)+b},easeInOutCirc:function(e,a,b,d,c){return 1>
(a/=c/2)?-d/2*(Math.sqrt(1-a*a)-1)+b:d/2*(Math.sqrt(1-(a-=2)*a)+1)+b},easeInElastic:function(e,a,b,d,c){e=0;var f=d;if(0==a)return b;if(1==(a/=c))return b+d;e||(e=.3*c);f<Math.abs(d)?(f=d,d=e/4):d=e/(2*Math.PI)*Math.asin(d/f);return-(f*Math.pow(2,10*--a)*Math.sin(2*(a*c-d)*Math.PI/e))+b},easeOutElastic:function(e,a,b,d,c){var f=0,l=d;if(0==a)return b;if(1==(a/=c))return b+d;f||(f=.3*c);l<Math.abs(d)?(l=d,e=f/4):e=f/(2*Math.PI)*Math.asin(d/l);return l*Math.pow(2,-10*a)*Math.sin(2*(a*c-e)*Math.PI/f)+
d+b},easeInOutElastic:function(e,a,b,d,c){var f=0,l=d;if(0==a)return b;if(2==(a/=c/2))return b+d;f||(f=.3*c*1.5);l<Math.abs(d)?(l=d,e=f/4):e=f/(2*Math.PI)*Math.asin(d/l);return 1>a?-.5*l*Math.pow(2,10*--a)*Math.sin(2*(a*c-e)*Math.PI/f)+b:l*Math.pow(2,-10*--a)*Math.sin(2*(a*c-e)*Math.PI/f)*.5+d+b},easeInBack:function(e,a,b,d,c,f){void 0==f&&(f=1.70158);return d*(a/=c)*a*((f+1)*a-f)+b},easeOutBack:function(e,a,b,d,c,f){void 0==f&&(f=1.70158);return d*((a=a/c-1)*a*((f+1)*a+f)+1)+b},easeInOutBack:function(e,
a,b,d,c,f){void 0==f&&(f=1.70158);return 1>(a/=c/2)?d/2*a*a*(((f*=1.525)+1)*a-f)+b:d/2*((a-=2)*a*(((f*=1.525)+1)*a+f)+2)+b},easeInBounce:function(e,a,b,d,c){return d-jQuery.easing.easeOutBounce(e,c-a,0,d,c)+b},easeOutBounce:function(e,a,b,d,c){return(a/=c)<1/2.75?7.5625*d*a*a+b:a<2/2.75?d*(7.5625*(a-=1.5/2.75)*a+.75)+b:a<2.5/2.75?d*(7.5625*(a-=2.25/2.75)*a+.9375)+b:d*(7.5625*(a-=2.625/2.75)*a+.984375)+b},easeInOutBounce:function(e,a,b,d,c){return a<c/2?.5*jQuery.easing.easeInBounce(e,2*a,0,d,c)+b:
.5*jQuery.easing.easeOutBounce(e,2*a-c,0,d,c)+.5*d+b}});
(function(e){e.fn.extend({easyResponsiveTabs:function(a){var b=a=e.extend({type:"default",width:"auto",fit:!0,closed:!1,activate:function(){}},a),d=b.type,c=b.fit,f=b.width;e(this).bind("tabactivate",function(c,d){"function"===typeof a.activate&&a.activate.call(d,c)});this.each(function(){var b=e(this),B=b.find("ul.resp-tabs-list");b.find("ul.resp-tabs-list li").addClass("resp-tab-item");b.css({display:"block",width:f});b.find(".resp-tabs-container > div").addClass("resp-tab-content");"vertical"==
d&&b.addClass("resp-vtabs");1==c&&b.css({width:"100%",margin:"0px"});"accordion"==d&&(b.addClass("resp-easy-accordion"),b.find(".resp-tabs-list").css("display","none"));var t;b.find(".resp-tab-content").before("<h2 class='resp-accordion' role='tab'><span class='resp-arrow'></span></h2>");var q=0;b.find(".resp-accordion").each(function(){t=e(this);var a=b.find(".resp-tab-item:eq("+q+")").html();b.find(".resp-accordion:eq("+q+")").append(a);t.attr("aria-controls","tab_item-"+q);q++});var g=0,h;b.find(".resp-tab-item").each(function(){$tabItem=
e(this);$tabItem.attr("aria-controls","tab_item-"+g);$tabItem.attr("role","tab");!0===a.closed||"accordion"===a.closed&&!B.is(":visible")||"tabs"===a.closed&&B.is(":visible")||(b.find(".resp-tab-item").first().addClass("resp-tab-active"),b.find(".resp-accordion").first().addClass("resp-tab-active"),b.find(".resp-tab-content").first().addClass("resp-tab-content-active").attr("style","display:block"));var c=0;b.find(".resp-tab-content").each(function(){h=e(this);h.attr("aria-labelledby","tab_item-"+
c);c++});g++});b.find("[role=tab]").each(function(){var a=e(this);a.click(function(){var c=a.attr("aria-controls");if(a.hasClass("resp-accordion")&&a.hasClass("resp-tab-active"))return b.find(".resp-tab-content-active").slideUp("",function(){e(this).addClass("resp-accordion-closed")}),a.removeClass("resp-tab-active"),!1;!a.hasClass("resp-tab-active")&&a.hasClass("resp-accordion")?(b.find(".resp-tab-active").removeClass("resp-tab-active"),b.find(".resp-tab-content-active").slideUp().removeClass("resp-tab-content-active resp-accordion-closed"),
b.find("[aria-controls="+c+"]").addClass("resp-tab-active"),b.find(".resp-tab-content[aria-labelledby = "+c+"]").slideDown().addClass("resp-tab-content-active")):(b.find(".resp-tab-active").removeClass("resp-tab-active"),b.find(".resp-tab-content-active").removeAttr("style").removeClass("resp-tab-content-active").removeClass("resp-accordion-closed"),b.find("[aria-controls="+c+"]").addClass("resp-tab-active"),b.find(".resp-tab-content[aria-labelledby = "+c+"]").addClass("resp-tab-content-active").attr("style",
"display:block"));a.trigger("tabactivate",a)});e(window).resize(function(){b.find(".resp-accordion-closed").removeAttr("style")})})})}})})(jQuery);
(function(e){e.fn.UItoTop=function(a){var b=e.extend({text:"To Top",min:200,inDelay:600,outDelay:400,containerID:"toTop",containerHoverID:"toTopHover",scrollSpeed:1E3,easingType:"linear"},a),d="#"+b.containerID,c="#"+b.containerHoverID;e("body").append('<a href="#" id="'+b.containerID+'">'+b.text+"</a>");e(d).hide().on("click.UItoTop",function(){e("html, body").animate({scrollTop:0},b.scrollSpeed,b.easingType);e("#"+b.containerHoverID,this).stop().animate({opacity:0},b.inDelay,b.easingType);return!1}).prepend('<span id="'+
b.containerHoverID+'"></span>').hover(function(){e(c,this).stop().animate({opacity:1},600,"linear")},function(){e(c,this).stop().animate({opacity:0},700,"linear")});e(window).scroll(function(){var a=e(window).scrollTop();"undefined"===typeof document.body.style.maxHeight&&e(d).css({position:"absolute",top:a+e(window).height()-50});a>b.min?e(d).fadeIn(b.inDelay):e(d).fadeOut(b.Outdelay)})}})(jQuery);
(function(e,a,b){e.fn.responsiveSlides=function(d){var c=e.extend({auto:!0,speed:500,timeout:4E3,pager:!1,nav:!1,random:!1,pause:!1,pauseControls:!0,prevText:"Previous",nextText:"Next",maxwidth:"",navContainer:"",manualControls:"",namespace:"rslides",before:e.noop,after:e.noop},d);return this.each(function(){b++;var f=e(this),l,B,t,q=0,g=f.children(),h=g.size(),w=parseFloat(c.speed),C=parseFloat(c.timeout),F=parseFloat(c.maxwidth),r=c.namespace,k=r+b,u=r+"_nav "+k+"_nav",m=r+"_here",n=k+"_on",D=k+
"_s",x=e("<ul class='"+r+"_tabs "+k+"_tabs' />"),E={"float":"left",position:"relative",opacity:1,zIndex:2},G={"float":"none",position:"absolute",opacity:0,zIndex:1},I=function(){var a=(document.body||document.documentElement).style,b="transition";if("string"===typeof a[b])return!0;l=["Moz","Webkit","Khtml","O","ms"];b=b.charAt(0).toUpperCase()+b.substr(1);var c;for(c=0;c<l.length;c++)if("string"===typeof a[l[c]+b])return!0;return!1}(),H=function(a){c.before(a);I?(g.removeClass(n).css(G).eq(a).addClass(n).css(E),
q=a,setTimeout(function(){c.after(a)},w)):g.stop().fadeOut(w,function(){e(this).removeClass(n).css(G).css("opacity",1)}).eq(a).fadeIn(w,function(){e(this).addClass(n).css(E);c.after(a);q=a})};c.random&&(g.sort(function(){return Math.round(Math.random())-.5}),f.empty().append(g));g.each(function(a){this.id=D+a});f.addClass(r+" "+k);d&&d.maxwidth&&f.css("max-width",F);g.hide().css(G).eq(0).addClass(n).css(E).show();I&&g.show().css({"-webkit-transition":"opacity "+w+"ms ease-in-out","-moz-transition":"opacity "+
w+"ms ease-in-out","-o-transition":"opacity "+w+"ms ease-in-out",transition:"opacity "+w+"ms ease-in-out"});if(1<g.size()){if(C<w+100)return;if(c.pager&&!c.manualControls){var p=[];g.each(function(a){a+=1;p+="<li><a href='#' class='"+D+a+"'>"+a+"</a></li>"});x.append(p);d.navContainer?e(c.navContainer).append(x):f.after(x)}c.manualControls&&(x=e(c.manualControls),x.addClass(r+"_tabs "+k+"_tabs"));(c.pager||c.manualControls)&&x.find("li").each(function(a){e(this).addClass(D+(a+1))});if(c.pager||c.manualControls){var z=
x.find("a");var A=function(a){z.closest("li").removeClass(m).eq(a).addClass(m)}}c.auto&&(B=function(){t=setInterval(function(){g.stop(!0,!0);var a=q+1<h?q+1:0;(c.pager||c.manualControls)&&A(a);H(a)},C)},B());var y=function(){c.auto&&(clearInterval(t),B())};c.pause&&f.hover(function(){clearInterval(t)},function(){y()});if(c.pager||c.manualControls)z.bind("click",function(a){a.preventDefault();c.pauseControls||y();a=z.index(this);q===a||e("."+n).queue("fx").length||(A(a),H(a))}).eq(0).closest("li").addClass(m),
c.pauseControls&&z.hover(function(){clearInterval(t)},function(){y()});if(c.nav){r="<a href='#' class='"+u+" prev'>"+c.prevText+"</a><a href='#' class='"+u+" next'>"+c.nextText+"</a>";d.navContainer?e(c.navContainer).append(r):f.after(r);k=e("."+k+"_nav");var v=k.filter(".prev");k.bind("click",function(a){a.preventDefault();a=e("."+n);if(!a.queue("fx").length){var b=g.index(a);a=b-1;b=b+1<h?q+1:0;H(e(this)[0]===v[0]?a:b);(c.pager||c.manualControls)&&A(e(this)[0]===v[0]?a:b);c.pauseControls||y()}});
c.pauseControls&&k.hover(function(){clearInterval(t)},function(){y()})}}if("undefined"===typeof document.body.style.maxWidth&&d.maxwidth){var J=function(){f.css("width","100%");f.width()>F&&f.css("width",F)};J();e(a).bind("resize",function(){J()})}})}})(jQuery,this,0);
(function(){function e(){if(document.body){var a=document.body,b=document.documentElement,c=window.innerHeight,e=a.scrollHeight;r=0<=document.compatMode.indexOf("CSS")?b:a;k=a;h.keyboardSupport&&window.addEventListener("keydown",d,!1);F=!0;top!=self?w=!0:e>c&&(a.offsetHeight<=c||b.offsetHeight<=c)&&(b.style.height="auto",r.offsetHeight<=c&&(c=document.createElement("div"),c.style.clear="both",a.appendChild(c)));h.fixedBackground||(a.style.backgroundAttachment="scroll",b.style.backgroundAttachment=
"scroll")}}function a(a,b,c,d){d||(d=1E3);B(b,c);if(1!=h.accelerationMax){var e=+new Date-x;e<h.accelerationDelta&&(e=(1+30/e)/2,1<e&&(e=Math.min(e,h.accelerationMax),b*=e,c*=e));x=+new Date}n.push({x:b,y:c,lastX:0>b?.99:-.99,lastY:0>c?.99:-.99,start:+new Date});if(!D){var p=a===document.body,f=function(e){e=+new Date;for(var z=0,y=0,A=0;A<n.length;A++){var v=n[A],g=e-v.start,l=g>=h.animationTime,k=l?1:g/h.animationTime;h.pulseAlgorithm&&(g=k,1<=g?k=1:0>=g?k=0:(1==h.pulseNormalize&&(h.pulseNormalize/=
q(1)),k=q(g)));g=v.x*k-v.lastX>>0;k=v.y*k-v.lastY>>0;z+=g;y+=k;v.lastX+=g;v.lastY+=k;l&&(n.splice(A,1),A--)}p?window.scrollBy(z,y):(z&&(a.scrollLeft+=z),y&&(a.scrollTop+=y));b||c||(n=[]);n.length?H(f,a,d/h.frameRate+1):D=!1};H(f,a,0);D=!0}}function b(b){F||e();var c=b.target,d=l(c);if(!d||b.defaultPrevented||"embed"===(k.nodeName||"").toLowerCase()||"embed"===(c.nodeName||"").toLowerCase()&&/\.pdf/i.test(c.src))return!0;c=b.wheelDeltaX||0;var f=b.wheelDeltaY||0;c||f||(f=b.wheelDelta||0);var p;if(p=
!h.touchpadSupport)if(p=f){p=Math.abs(p);u.push(p);u.shift();clearTimeout(I);p=u[0]==u[1]&&u[1]==u[2];var g=t(u[0],120)&&t(u[1],120)&&t(u[2],120);p=!(p||g)}else p=void 0;if(p)return!0;1.2<Math.abs(c)&&(c*=h.stepSize/120);1.2<Math.abs(f)&&(f*=h.stepSize/120);a(d,-c,-f);b.preventDefault()}function d(b){var c=b.target,d=b.ctrlKey||b.altKey||b.metaKey||b.shiftKey&&b.keyCode!==m.spacebar;if(/input|textarea|select|embed/i.test(c.nodeName)||c.isContentEditable||b.defaultPrevented||d||"button"===(c.nodeName||
"").toLowerCase()&&b.keyCode===m.spacebar)return!0;var e=c=0;d=l(k);var f=d.clientHeight;d==document.body&&(f=window.innerHeight);switch(b.keyCode){case m.up:e=-h.arrowScroll;break;case m.down:e=h.arrowScroll;break;case m.spacebar:e=b.shiftKey?1:-1;e=-e*f*.9;break;case m.pageup:e=.9*-f;break;case m.pagedown:e=.9*f;break;case m.home:e=-d.scrollTop;break;case m.end:f=d.scrollHeight-d.scrollTop-f;e=0<f?f+10:0;break;case m.left:c=-h.arrowScroll;break;case m.right:c=h.arrowScroll;break;default:return!0}a(d,
c,e);b.preventDefault()}function c(a){k=a.target}function f(a,b){for(var c=a.length;c--;)E[G(a[c])]=b;return b}function l(a){var b=[],c=r.scrollHeight;do{var d=E[G(a)];if(d)return f(b,d);b.push(a);if(c===a.scrollHeight){if(!w||r.clientHeight+10<c)return f(b,document.body)}else if(a.clientHeight+10<a.scrollHeight&&(overflow=getComputedStyle(a,"").getPropertyValue("overflow-y"),"scroll"===overflow||"auto"===overflow))return f(b,a)}while(a=a.parentNode)}function B(a,b){a=0<a?1:-1;b=0<b?1:-1;if(C.x!==
a||C.y!==b)C.x=a,C.y=b,n=[],x=0}function t(a,b){return Math.floor(a/b)==a/b}function q(a){a*=h.pulseScale;if(1>a)var b=a-(1-Math.exp(-a));else b=Math.exp(-1),a=1-Math.exp(-(a-1)),b+=a*(1-b);return b*h.pulseNormalize}var g={frameRate:150,animationTime:1800,stepSize:85,pulseAlgorithm:!0,pulseScale:8,pulseNormalize:1,accelerationDelta:20,accelerationMax:1,keyboardSupport:!0,arrowScroll:50,touchpadSupport:!0,fixedBackground:!0,excluded:""},h=g,w=!1,C={x:0,y:0},F=!1,r=document.documentElement,k,u=[120,
120,120],m={left:37,up:38,right:39,down:40,spacebar:32,pageup:33,pagedown:34,end:35,home:36};h=g;var n=[],D=!1,x=+new Date,E={};setInterval(function(){E={}},1E4);var G=function(){var a=0;return function(b){return b.uniqueID||(b.uniqueID=a++)}}(),I,H=function(){return window.requestAnimationFrame||window.webkitRequestAnimationFrame||function(a,b,c){window.setTimeout(a,c||1E3/60)}}();g=/chrome/i.test(window.navigator.userAgent);"onmousewheel"in document&&g&&(window.addEventListener("mousedown",c,!1),
window.addEventListener("mousewheel",b,!1),window.addEventListener("load",e,!1))})();